# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf4c779259de11e69362150ed70a9533"
name = "feisty-voice-studio"
handle = "feisty-voice-studio"
application_url = "https://brazil-state-yen-easy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "feistyagency.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_product_listings,read_customers,read_content"

[auth]
redirect_urls = [
  "https://brazil-state-yen-easy.trycloudflare.com/auth/callback",
  "https://brazil-state-yen-easy.trycloudflare.com/auth/shopify/callback",
  "https://brazil-state-yen-easy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[app_env.production]
REPLICATE_API_TOKEN = "__PLACEHOLDER__"
ULTRAVOX_MODEL_VERSION = "__PLACEHOLDER__"

[app_env.development]
REPLICATE_API_TOKEN = "__PLACEHOLDER__"
ULTRAVOX_MODEL_VERSION = "__PLACEHOLDER__"

[pos]
embedded = false

[app_proxy]
url = "https://brazil-state-yen-easy.trycloudflare.com/proxy"
prefix = "apps"
subpath = "voice"
