# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf4c779259de11e69362150ed70a9533"
name = "feisty-voice-studio"
handle = "feisty-voice-studio"
application_url = "https://subject-forums-dried-travelling.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "feistyagency.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://subject-forums-dried-travelling.trycloudflare.com/auth/callback",
  "https://subject-forums-dried-travelling.trycloudflare.com/auth/shopify/callback",
  "https://subject-forums-dried-travelling.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
